spring:
  main:
    banner-mode: off
  application:
    name: Builders MVP
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:buiders-mvp.db
  jpa:
      hibernate:
        ddl-auto: update
      database-platform: br.com.felipestoco.buildersmvp.config.SQLDialect
      properties:
        show-sql: true
        format-sql: true
  profiles:
    active: dev

server:
  port: 9001
  servlet:
    context-path: /buildersmvp/api/v1

springdoc:
  api-docs:
    path: /api-docs