spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:builders-mvp-test
    username: sa
    password:
