spring:
  main:
    banner-mode: off
  application:
    name: Builders MVP
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: ${BUILDERSMVP_DATABASE_URL}
  jpa:
      hibernate:
        ddl-auto: update
      database-platform: br.com.felipestoco.buildersmvp.config.SQLDialect
      properties:
        show-sql: true
        format-sql: true

server:
  port: ${PORT}
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs